# .github/workflows/go.yml
name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Navigate to the 'day1' directory
      - name: Navigate to day1 directory
        run: cd day1

      # Install dependencies
      - name: Install dependencies
        run: |
          cd day1
          go mod tidy

      # Build the project
      - name: Build
        run: |
          cd day1
          go build -v ./...

      # Run tests
      - name: Test
        run: |
          cd day1
          go test -v ./...
